### ISSUE TITLE
Is it compatible with Spring framework?

### ISSUE THREAD

**Issue by gusbemacbe** [wmixvideo/correios-web#1]
Hello,

I would like to know if it is compatible with Spring framework. I use JSP files. My Spring's version is latest (2.0.1) and Java’s is 9.

Olá,

Eu gostaria de saber se é compatível com a modelagem de Spring. Utilizo os ficheiros no formato JSP. Minha versão de Srping é mais recente (2.0.1) e a de Java é 9.

**Comment by fincatto** [comment]
Na verdade, este modulo é feito para rodar sozinho e provê os dados em varios formatos, como html, xml e json.
Se você quiser integrar a nivel de codigo, existe outro projeto (https://github.com/wmixvideo/correios) que permite que você integre a nivel de codigo, com qualquer framework.
